global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'postgres-service'
    static_configs:
      - targets: ['host.docker.internal:3001']
    metrics_path: '/metrics'

  - job_name: 'redis-service'
    static_configs:
      - targets: ['host.docker.internal:3002']
    metrics_path: '/metrics'

  - job_name: 'bloom-service'
    static_configs:
      - targets: ['host.docker.internal:3003']
    metrics_path: '/metrics'
