global:
  scrape_interval: 2s # Fast scraping for real-time demo

scrape_configs:
  - job_name: 'rest-service'
    static_configs:
      - targets: ['host.docker.internal:3001']

  - job_name: 'kafka-producer'
    static_configs:
      - targets: ['host.docker.internal:3002']

  - job_name: 'kafka-consumer'
    static_configs:
      - targets: ['host.docker.internal:3003'] # We will add a metrics port to consumer
